In [4]:
import numpy as np
A = np.arange(20)
a1 = A [:10]
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a1[:] = 100
print(a1, A)

[100 100 100 100 100 100 100 100 100 100] [100 100 100 100 100 100 100 100 100 100  10  11  12  13  14  15  16  17
  18  19]


In [11]:
x = list(range(20))
print(x)
y = x[:10]
y[0] = 100
print(y)
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[100, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [12]:
A = np.arange(20)
print(A)
B = A.copy()
print(B)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
B[0] = 5
print(B)
print(A)

[ 5  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


3

In [14]:
C = np.array([1, 4, 3, 6, 8, 0, 2, 10])
C[2]

3

In [18]:
# Khi sử dụng Range và Arange tạo phần tử thì khi gọi phần tử sẽ gọi ra giá trị của nó
print(B[3])
D = list(range(8))
D[4]

3


4