In [26]:
import numpy as np
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [27]:
b = np.arange(25)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
# Sắp xếp hình dạng của mảng dùng reshape
b.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
# Viết gộp tạo mảng bằng arange rồi sắp xếp hình dạng cột dòng 
c = np.arange(25).reshape(5,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
abc = np.array([[3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6]])
abc.shape

(2, 6)

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

- zeros_like
Return an array of zeros with shape and type of input.
- ones_like
Return an array of ones with shape and type of input.
- empty_like
Return an empty array with shape and type of input.
- ones
Return a new array setting values to one.
- empty
Return a new uninitialized array.

<!-- Dịch -->
- zeros_like
Trả về một mảng số 0 với hình dạng và loại đầu vào.
- ones_like
Trả về một loạt các loại có hình dạng và loại đầu vào.
- empty_like
Trả về một mảng trống với hình dạng và loại đầu vào.
những
- ones
Trả về giá trị thiết đặt mảng mới cho một.
trống
- empty
Trả về một mảng chưa được phân biệt mới.

In [34]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.empty(8)

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.11658836e-320, 0.00000000e+000, 1.94693963e-308])

In [40]:
np.ones_like(8)

array(1)