In [1]:
# Phép toán trong Array
import numpy as np
arra = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [2]:
# Cộng
arrb = arra + 10
print(arrb)

[[11 12 13 14]
 [15 16 17 18]]


In [3]:
# Trừ
arrc = arra - 3
print(arrc)

[[-2 -1  0  1]
 [ 2  3  4  5]]


In [5]:
# Nhân 
arrd = arra * arra
print(arrd)

[[ 1  4  9 16]
 [25 36 49 64]]


In [6]:
# Chia 
arre = arra / 2
print(arre)

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]]


In [9]:
# Lũy thừa
arrf = arra ** 2
print(arrf)
print(arra**5)

[[ 1  4  9 16]
 [25 36 49 64]]
[[    1    32   243  1024]
 [ 3125  7776 16807 32768]]


In [13]:
# Transpose: Đảo dòng thành cột, cột thành dòng
A = np.arange(25).reshape(5,5)
print(A)
print(A.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [16]:
B = np.arange(6).reshape(2,3)
print(B)
print(B.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
