In [9]:
import numpy as np 
x = []
y = []
for i in range(10) :
    x.append(np.random.randint(1,10))
    y.append(np.random.randint(1,10))
print(x,y)


[2, 2, 5, 6, 1, 1, 4, 8, 8, 3] [7, 1, 4, 6, 2, 8, 8, 4, 8, 5]


In [15]:
x = np.array(x)
y = np.array(y)
# Sắp xếp theo thứ tự tăng dần
print(x,y)
x.sort()
y.sort()


[1 1 2 2 3 4 5 6 8 8] [1 2 4 4 5 6 7 8 8 8]


In [19]:
# Lọc các phần tử trùng nhau ra
a = np.unique(x)
print(a)
np.unique(y)

[1 2 3 4 5 6 8]


array([1, 2, 4, 5, 6, 7, 8])

In [21]:
import numpy as np
x = []
y = []
for i in range(10) :
    x.append(np.random.randint(1,10))
    y.append(np.random.randint(1,10))
print(x,y)
x = np.array(x)
y = np.array(y)
print(x,y)

[2, 9, 4, 3, 8, 1, 4, 3, 4, 5] [1, 9, 1, 7, 6, 1, 3, 2, 8, 1]
[2 9 4 3 8 1 4 3 4 5] [1 9 1 7 6 1 3 2 8 1]


In [23]:
# So sánh x lớn hơn y không, đúng thì in ra True
np.greater(x,y)

array([ True, False,  True, False,  True, False,  True,  True, False,
        True])

In [24]:
np.greater(y,x)

array([False, False, False,  True, False, False, False, False,  True,
       False])

In [30]:
# Kiểm tra tất cả phần tử của x có lớn hơn y không, đúng thì in ra True, sai thì False
b = np.greater(x,y)
print(b)
b.all()

[ True False  True False  True False  True  True False  True]


False

In [32]:
# Kiểm tra có phần tử của x có lớn hơn y không, đúng thì in ra True, sai thì False
b.any()

True

In [33]:
# So sánh bằng
np.equal(x,y)

array([False,  True, False, False, False,  True, False, False, False,
       False])

In [35]:
u = np.array([1, 2, 3, 4, 5, 6, 7, 8])
z = np.array([2, 1, 3, 4, 5, 9, 6, 7])
np.equal(u,z)

array([False, False,  True,  True,  True, False, False, False])

In [38]:
k = np.array([1, 2, 3, 4, 5, 6, 7, 8])
m = np.array([1, 2, 3, 4, 5, 6, 7, 8])
i = np.equal(k,m)
i.all()
i.any()


True