In [8]:
# Hàm random 
import numpy as np
x = np.random.randint(1,10)
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [5]:
x

7

In [12]:
# Các phần tử trong x, y random với nhau đến khi end
x = []
y = []
for i in range(10) :
    x.append(np.random.randint(1,10))
    y.append(np.random.randint(1,10))


In [10]:
x,y

([6, 2, 3, 7, 9, 4, 3, 5, 9, 1], [4, 7, 7, 1, 9, 1, 6, 6, 2, 5])

In [14]:
x = np.array(x)
y = np.array(y)
print(x,y)

[3 6 2 7 9 9 4 7 6 8] [6 1 3 1 4 9 6 5 4 9]


In [16]:
# Lấy từng phần tử ở vị trí giống nhau cộng với nhau
np.add(x,y)

array([ 9,  7,  5,  8, 13, 18, 10, 12, 10, 17])

In [20]:
# Kiểm tra các phần tử ở vị trí giống nhau của từng mảng, phần tử nào có giá trị lớn hơn/ nhỏ hơn thì lấy
print(x)
print(y)
print(np.maximum(x,y))
np.minimum(x,y)

[3 6 2 7 9 9 4 7 6 8]
[6 1 3 1 4 9 6 5 4 9]
[6 6 3 7 9 9 6 7 6 9]


array([3, 1, 2, 1, 4, 9, 4, 5, 4, 8])

In [21]:
# Căn bậc hai
np.sqrt(x)

array([1.73205081, 2.44948974, 1.41421356, 2.64575131, 3.        ,
       3.        , 2.        , 2.64575131, 2.44948974, 2.82842712])

In [22]:
# Bình phương
np.square(x)

array([ 9, 36,  4, 49, 81, 81, 16, 49, 36, 64])

In [23]:
# Lấy mảng x / y
np.divide(x,y)

array([0.5       , 6.        , 0.66666667, 7.        , 2.25      ,
       1.        , 0.66666667, 1.4       , 1.5       , 0.88888889])

In [25]:
# Lấy x mũ y
np.power(x,y)

array([      729,         6,         8,         7,      6561, 387420489,
            4096,     16807,      1296, 134217728])