In [4]:
import numpy as np
A = np.arange(20).reshape(4,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
# Lấy phần tử của mảng, start là index tính từ 0, end index tính từ 1
print(A[0])
print(A[2][2])
print(A[2:4,1:4])

[0 1 2 3 4]
12
[[11 12 13]
 [16 17 18]]


In [14]:
print(A[[0, 2, 3]])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [16]:
# Côngj hết phần tử ngang dọc lại với nhau
A.sum()

190