In [1]:
import numpy as np
a = [1, 2, 3, 4]
print(type(a))

<class 'list'>


In [2]:
# Chuyển list sang Numpy
arr = np.array(a)
print(type(a))

<class 'list'>


In [3]:
b = [5, 6, 7, 8]
arrb = np.array(b)
print(type(b))

<class 'list'>


In [4]:
print(arr, arrb)

[1 2 3 4] [5 6 7 8]


In [5]:
c = [9, 10, 11, 12]
arrc = np.array(c)
print(arrc)

[ 9 10 11 12]


In [6]:
# Phép toán trên mảng:
tongarr = np.array([arr, arrb, arrc])
print(tongarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# Kích thước numpy 
print(tongarr)
tongarr.shape # 3 dòng, 4 cột

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [8]:
# hàm tạo phần tử trong list range sang numpy tạo phần tử trong array chuyển thành arange
A = np.arange(10)
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
B = np.arange(4, 9) # start là giá trị, end là giá trị tại index
print(B)

[4 5 6 7 8]
